import Head from 'next/head'
import Products from '../components/products'
import Navbar from '../components/navbar'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const res = await fetch('https://fakestoreapi.com/products')
  const json = await res.json()
  const posts = json
  return {
    props: {
      posts
    }
  }
}

export default function Home({ posts }) {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className='container mx-auto py-10 flex flex-col justify-center'>

        <Products products={posts} />
      </main>

    </div>
  )
}
